틀린 것 비교

In [3]:
import numpy as np
import pandas as pd

데이터 불러오기

In [4]:
random1_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_random1.npy')
random2_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_random2.npy')
random3_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_random3.npy')
cosine_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_cosine.npy')
clustering_1_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_clustering(1).npy')
clustering_2_array = np.load('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/unlabeled_probabilities_clustering(2).npy')

소프트 라벨을 하드 라벨로(임계값 = 0,5)

In [5]:
random1_array_hard = np.argmax(random1_array, axis=1)
random2_array_hard = np.argmax(random2_array, axis=1)
random3_array_hard = np.argmax(random3_array, axis=1)
cosine_array_hard = np.argmax(cosine_array, axis=1)
clustering_1_array_hard = np.argmax(clustering_1_array, axis=1)
clustering_2_array_hard = np.argmax(clustering_2_array, axis=1)

In [6]:
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_random1.npy', random1_array_hard)
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_random2.npy', random2_array_hard)
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_random3.npy', random3_array_hard)
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_cosine.npy', cosine_array_hard)
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_clustering(1).npy', clustering_1_array_hard)
np.save('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/classification/hard_label_clustering(2).npy', clustering_2_array_hard)

In [7]:
random1_array_hard = np.where(random1_array_hard == 0, 1, np.where(random1_array_hard == 1, 2, random1_array_hard))
random2_array_hard = np.where(random2_array_hard == 0, 1, np.where(random2_array_hard == 1, 2, random2_array_hard))
random3_array_hard = np.where(random3_array_hard == 0, 1, np.where(random3_array_hard == 1, 2, random3_array_hard))
cosine_array_hard = np.where(cosine_array_hard == 0, 1, np.where(cosine_array_hard == 1, 2, cosine_array_hard))
clustering_1_array_hard = np.where(clustering_1_array_hard == 0, 1, np.where(clustering_1_array_hard == 1, 2, clustering_1_array_hard))
clustering_2_array_hard = np.where(clustering_2_array_hard == 0, 1, np.where(clustering_2_array_hard == 1, 2, clustering_2_array_hard))

unlabeled dataframe

In [8]:
df_unlabeled = pd.read_csv("C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/df_unlabeled.csv")

In [9]:
df_unlabeled

                                                   text  label
0     They need better beer if I will ever get my hu...      1
1     I had always been aware that this place was he...      2
2     Fake and shake! Not like the original at all! ...      1
3     There is a lot of different stuff with lots of...      1
4     I am a big fan of Starwood hotels and have dec...      2
...                                                 ...    ...
9995  Let's get the cons out of the way n nI know it...      2
9996  There once was a businessman who walked into a...      2
9997  CLOSED! n nThey have moved to San Tan Village....      1
9998  My sons, my husband, and I love this place! We...      2
9999  We were only in Charlotte for one night, and D...      2

[10000 rows x 2 columns]

새로운 열로 추가

In [10]:
df_unlabeled["random1_label"] = random1_array_hard
df_unlabeled["random2_label"] = random2_array_hard
df_unlabeled["random3_label"] = random3_array_hard
df_unlabeled["cosine_label"] = cosine_array_hard
df_unlabeled["clustering_1_label"] = clustering_1_array_hard
df_unlabeled["clustering_2_label"] = clustering_2_array_hard

In [11]:
df_unlabeled

,text,label,random1_label,random2_label,random3_label,cosine_label,clustering_1_label,clustering_2_label
0,They need better beer if I will ever get my hu...,1,1,1,1,1,1,1
1,I had always been aware that this place was he...,2,2,2,2,2,2,2
2,Fake and shake! Not like the original at all! ...,1,1,1,1,1,1,1
3,There is a lot of different stuff with lots of...,1,1,1,1,1,1,1
4,I am a big fan of Starwood hotels and have dec...,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...
9995,Let's get the cons out of the way n nI know it...,2,2,1,2,2,1,1
9996,There once was a businessman who walked into a...,2,2,2,2,2,2,2
9997,CLOSED! n nThey have moved to San Tan Village....,1,1,1,1,1,1,1
9998,"My sons, my husband, and I love this place! We...",2,2,2,2,2,2,2
9999,"We were only in Charlotte for one night, and D...",2,2,2,2,2,2,2

틀린 값 찾기_엑셀로 저장

In [11]:
wrong_answer_random_1 = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['random1_label']]
wrong_answer_random_2 = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['random2_label']]
wrong_answer_random_3 = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['random3_label']]
wrong_answer_cosine = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['cosine_label']]
wrong_answer_clustering_1 = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['clustering_1_label']]
wrong_answer_clustering_2 = df_unlabeled.index[df_unlabeled['label'] != df_unlabeled['clustering_2_label']]

In [12]:
df_wrong_answer_random_1 = df_unlabeled.loc[wrong_answer_random_1]
df_wrong_answer_random_2 = df_unlabeled.loc[wrong_answer_random_2]
df_wrong_answer_random_3 = df_unlabeled.loc[wrong_answer_random_3]
df_wrong_answer_cosine = df_unlabeled.loc[wrong_answer_cosine]
df_wrong_answer_clustering_1 = df_unlabeled.loc[wrong_answer_clustering_1]
df_wrong_answer_clustering_2 = df_unlabeled.loc[wrong_answer_clustering_2]

In [13]:
wrong_answer_writer = pd.ExcelWriter('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/result_df/wrong_answers.xlsx', engine='xlsxwriter')

In [14]:
df_wrong_answer_random_1.to_excel(wrong_answer_writer, sheet_name='random_1', index=True)
df_wrong_answer_random_2.to_excel(wrong_answer_writer, sheet_name='random_2', index=True)
df_wrong_answer_random_3.to_excel(wrong_answer_writer, sheet_name='random_3', index=True)
df_wrong_answer_cosine.to_excel(wrong_answer_writer, sheet_name='cosine', index=True)
df_wrong_answer_clustering_1.to_excel(wrong_answer_writer, sheet_name='clustering_1', index=True)
df_wrong_answer_clustering_2.to_excel(wrong_answer_writer, sheet_name='clustering_2', index=True)

In [15]:
wrong_answer_writer.save()

C:\Users\user\AppData\Local\Temp\ipykernel_32992\772461091.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  wrong_answer_writer.save()

유사도 기준으로 유사도는 맞았는데, 다른 기준은 틀린 값

In [17]:
df_difference_random_1 = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) & (df_unlabeled['label'] != df_unlabeled['random1_label']), ['text', 'label','cosine_label','random1_label']]
df_difference_random_2 = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) & (df_unlabeled['label'] != df_unlabeled['random2_label']), ['text', 'label','cosine_label','random2_label']]
df_difference_random_3 = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) & (df_unlabeled['label'] != df_unlabeled['random3_label']), ['text', 'label','cosine_label','random3_label']]
df_difference_clustering_1 = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) & (df_unlabeled['label'] != df_unlabeled['clustering_1_label']), ['text', 'label','cosine_label','clustering_1_label']]
df_difference_clustering_2 = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) & (df_unlabeled['label'] != df_unlabeled['clustering_2_label']), ['text', 'label','cosine_label','clustering_2_label']]

In [18]:
different_answer_writer = pd.ExcelWriter('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/result_df/different_answers.xlsx', engine='xlsxwriter')

In [19]:
df_difference_random_1.to_excel(different_answer_writer, sheet_name='random_1', index=True)
df_difference_random_2.to_excel(different_answer_writer, sheet_name='random_2', index=True)
df_difference_random_3.to_excel(different_answer_writer, sheet_name='random_3', index=True)
df_difference_clustering_1.to_excel(different_answer_writer, sheet_name='clustering_1', index=True)
df_difference_clustering_2.to_excel(different_answer_writer, sheet_name='clustering_2', index=True)

In [20]:
different_answer_writer.save()

C:\Users\user\AppData\Local\Temp\ipykernel_32992\1482095935.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  different_answer_writer.save()

# 유사도만 맞춘 값

In [12]:
only_cosine = df_unlabeled.loc[(df_unlabeled['label'] == df_unlabeled['cosine_label']) &
                               (df_unlabeled['label'] != df_unlabeled['random1_label']) &
                               (df_unlabeled['label'] != df_unlabeled['random2_label']) &
                               (df_unlabeled['label'] != df_unlabeled['random3_label']) &
                               (df_unlabeled['label'] != df_unlabeled['clustering_1_label']) &
                               (df_unlabeled['label'] != df_unlabeled['clustering_2_label']),
                               ['text', 'label','cosine_label','random1_label', 'random2_label','random3_label', 'clustering_1_label','clustering_2_label']
]

In [19]:
only_cosine

,text,label,cosine_label,random1_label,random2_label,random3_label,clustering_1_label,clustering_2_label
223,"The food was awesome.the service, not so much....",2,2,1,1,1,1,1
698,For those of us who like good clothing but are...,2,2,1,1,1,1,1
755,Treacherous! Bring a DD and have fun!,2,2,1,1,1,1,1
2832,Not everything has to stay in vegas,2,2,1,1,1,1,1
2971,do i feel stupid that i'm always the only litt...,2,2,1,1,1,1,1
3061,My wife will literally punch a baby seal in th...,2,2,1,1,1,1,1
3104,Vons is expensive. I barely go to any grocery ...,2,2,1,1,1,1,1
4588,Just wanted to write a note that this location...,2,2,1,1,1,1,1
4589,My daughter and I went to this mall for a casu...,2,2,1,1,1,1,1
4866,I can honestly admit I'm a lazy person when it...,2,2,1,1,1,1,1
5360,Went on a wednesday at 2 30 pm and I was the o...,2,2,1,1,1,1,1
6531,My only complaint is that they only have brunc...,2,2,1,1,1,1,1
7576,"Before I even start, I want to make note that ...",1,1,2,2,2,2,2
9193,FETALICIOIUS. n nThat is all.,2,2,1,1,1,1,1
9781,"This is my 300th review. nThe end. nHahahaha, ...",2,2,1,1,1,1,1
9977,Omg all i have to say is get the mac n' cheese...,2,2,1,1,1,1,1

In [20]:
only_cosine_writer = pd.ExcelWriter('C:/Users/user/Desktop/논문리뷰/Pattern-Exploiting-Training(PET)/code/testPET - 복사본/data_2/result_df/only_cosine.xlsx', engine='xlsxwriter')

In [21]:
only_cosine.to_excel(only_cosine_writer, sheet_name='only_cosine', index=True)

In [22]:
only_cosine_writer.save()

C:\Users\user\AppData\Local\Temp\ipykernel_33628\3780706832.py:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  only_cosine_writer.save()